/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.2/userguide/tutorial_java_projects.html
 */
import org.springframework.boot.gradle.tasks.bundling.BootJar
import org.springframework.boot.gradle.tasks.bundling.BootWar
import com.github.jengelman.gradle.plugins.shadow.ShadowExtension
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import ratpack.gradle.RatpackExtension

plugins {
    // Apply the java plugin to add support for Java
    java
    application
	war
`java-library`
	id("org.springframework.boot")  version "2.1.9.RELEASE"
	    id("com.github.johnrengelman.shadow") version "4.0.1" apply false
    id("io.ratpack.ratpack-java") version "1.5.4" apply false
}

allprojects {
	apply(plugin = "io.spring.dependency-management")
	
	group = "com.eascapeco.sinemapr"
    version = "1.0.0"
	
	repositories {
        mavenCentral()
    }
}


//tasks.getByName<BootJar>("bootJar") {
//	mainClassName = "test2.App"
//}

//tasks.getByName<BootWar>("bootWar") {
//	mainClassName = "test2.App"
//}

subprojects {

}

project("scinemapr.core") {
	apply(plugin = "java-library")
	
    dependencies {
		implementation("org.apache.commons:commons-lang3:3.9")
    }
}

project("scinemapr.api") {
	apply(plugin = "java-library")
	
    dependencies {
    }
}

project("scinemapr.bo") {
    apply(plugin = "java-library")
	
	dependencies {
    
	}
}
