spring:
  datasource:
    driver-class-name: 
    url: 
    username: 
    password: 
  thymeleaf:
    prefix: classpath:static/
    check-template-location: false
    suffix: .html
    mode: HTML
    cache: false
    template-resolver-order: 0
logging:
  level:
    root: warn
